sourcegraph/deploy

dev/override.XL.yaml

Updating with the latest config values based on the reference architecture testing and postgres config
I've copied the values directly from what was used for the testing. 
In practice the reduced limits on memory for indexSearch, indexedSearchIndexer and Searcher should cause no issues in all but outlier cases.
There shouldn't me memory contention anyway so to err on the side of caution I can revert the memory reductions if you'd prefer.

Update XL config

---

ami/packer/ami-builder.pkr.hcl
install/install.sh
install/reboot.sh

- Fix launch script file permission issue
- Confirmed the script `ami-builder.pkr.hcl` worked with the updated launch script as I was able to build multiple amis in parallel (only tested with 2): 
```bash
Build 'sourcegraph-amis.amazon-ebs.size-s' finished after 5 minutes 24 seconds.
==> Wait completed after 5 minutes 24 seconds
==> Builds finished. The artifacts of successful builds are:
--> sourcegraph-amis.amazon-ebs.size-xs: AMIs were created:
us-west-2: ami-04824869ac44cf3ff
--> sourcegraph-amis.amazon-ebs.size-s: AMIs were created:
us-west-2: ami-0f3bc54f6d3ad7ffc
```

Add parallel build script + fix file permission issue

---

install/scripts/k3s/local.sh

Add k3s local installation scripts for `brew install sourcegraph` / `brew install sgup` (name undecided, but you can see [the demos here](https://github.com/sourcegraph/sourcegraph/issues/44121#issuecomment-1309743999)) to run `curl` with to simplify the installation step. 
Also adding to docs for installing locally: https://github.com/sourcegraph/sourcegraph/pull/43576
Instead of manually downloading the scripts to run, users can now run a simple curl command to install k3s instance on their local linux machine:
```bash
curl -sfL https://raw.githubusercontent.com/sourcegraph/deploy/main/install/scripts/k3s/local.sh | bash
```
To add version number:
```bash
curl -sfL https://raw.githubusercontent.com/sourcegraph/deploy/main/install/scripts/k3s/local.sh | bash - v4.1.3
```

Add k3s local installation scripts

---

install/override.L.yaml
install/override.M.yaml
install/override.S.yaml
install/override.XL.yaml
install/override.XS.yaml

Current override files are misconfigured using the wrong keys for replicas and preciseCodeIntel service.
When I deploy using the XS override yaml file,  the resources are configured correctly but the values for replicas are not being respected. For example, two seachers and are deployed using the XS override file when we have specified replicas: 1:
```
default       precise-code-intel-worker-67f57fdfbf-jg76l   1/1     Running             1 (102m ago)   3d19h
default       precise-code-intel-worker-67f57fdfbf-r277n   1/1     Running             1 (102m ago)   3d19h
default       searcher-7648cd658d-skbx7                    0/1     Pending             0               3d17h
default       searcher-7648cd658d-q797c                    0/1     Pending             0               3d17h
```
This …

Fix replicaCount keys for override files

---

install/scripts/k3s/install.sh

Generic install script for customers to use if they can't use a machine image or we don't have a machine image for their preferred platform.
Adapted from @abeatrix's script in this [PR](https://github.com/sourcegraph/deploy/pull/17).
The primary changes I made are:
- Removed Install Wizard as that is still in testing
- Made data disk setup independent from the base distro
- Add support to optionally deploy with `--selinux` if on a system where policies are permissive/enforced
- Added support to pass in a data disk instead of hard coding `/dev/sdb`
Can be run like so:
```
curl -sfL https://raw.githubusercontent.com/sourcegraph/deploy/a337d3f1ac41e0018be09ac4e54168054bcdef78/install/scripts/k3s/install.sh | bash -s -- <args>
```
Supported args are:
- `-d <path>` data disk to use. Required
- …

Add generic install script

---

install/override.L.yaml
install/override.M.yaml
install/override.S.yaml
install/override.XL.yaml
install/override.XS.yaml

We didn't have an override for openTelemetry meaning it was requesting the default values of 1 vCPU, 1GiB of RAM.
This caused an insufficient CPU issue on our recommended machine size of 8 CPU for XS

Add override for openTelemetry

---

install/scripts/k3s/install.sh
install/scripts/k3s/reboot.sh

Clone the reboot script and run as the same user who ran the install script
TODO unify all the scripts - I didn't want to block the AMIs by making changes there without having time to test

Reboot script should run as current user

---

packer/aws-latest/aws-builder.pkr.hcl
packer/aws/aws-builder.pkr.hcl

Cleanup keys that are left behind from packer during the build process. These were flagged by AWS Marketplace evaluation.

AWS images: remove left over keys from build process

---

packer/gcp/init.sh
packer/gcp/install.sh

Fixes the symlink issue.
At the end of init; kill k3s; create broken symlinks to data dir.
At start of install. If existing disk then everything just works. Otherwise set up disk & dirs
- Possible known issue
- k3s can complain about node name reuse; restarting k3s fixes it
Tested images

Fix GCP symlinks

---

CHANGELOG.md

Does not include native k8s executors due to them only getting added to the helm deployment the day of 5.1 release.

5.1.1 AMIs

---

CHANGELOG.md
install/reboot.sh

Resolves #57, https://github.com/sourcegraph/customer/issues/3145 and [REL-1](https://linear.app/sourcegraph/issue/REL-1/upgrading-aws-ami-instance-fails-without-internet-connectivity) by deleting pods in the `reboot.sh` script. 
Tested manually. It does work, but it does mean a bit more waiting on booting the new AMI (about 5 minutes)

fix: AMIs on restart not booting up

---

install/reboot.sh

Fix for issue where air-gapped AMIs fail to init after initial reboots. While issues this seems to be intermittent, this fix reliably solves the issue in our testing, while also increasing initial boot times.
closes https://linear.app/sourcegraph/issue/REL-147/bug-in-v545099-aws-ami-containers-not-restarting-after-reboot

Fix: delete pods on all restarts

---

.buildkite/pipeline.yml

Remove the extra "v" that was causing [this](https://linear.app/sourcegraph/issue/REL-111/543643-helm-charts-no-longer-contain-v-in-the-targz-leading-to-ami) failure
Resolves [REL-111](https://linear.app/sourcegraph/issue/REL-111/543643-helm-charts-no-longer-contain-v-in-the-targz-leading-to-ami)

fix(ci): Remove extra "v" from $RELEASE_NUMBER

---

.buildkite/pipeline.yml

Resolves [REL-206](https://linear.app/sourcegraph/issue/REL-206/ami-automation-buildkite-pipeline-busted)
Our pipeline was failing because I didn't escape the new line in https://github.com/sourcegraph/deploy/pull/91

Fix: Broken pipeline due to unescaped `$(...)`

---

install/reboot.sh

to enable customers to make customizations and have them persist on the data volume, instead of getting reset the next time they upgrade the AMI. For cases like [GRAPH-809](https://linear.app/sourcegraph/issue/GRAPH-809/scip-index-ingestion-failure-bad-connectionconn-closed).

Add the option to store a custom Helm override file on the AMI's data volume

---

install/install.sh

This PR fixes the install script such that it can install required selinux dependencies (even though SELinux is still disabled? I'm not sure if it was ever enabled...)
Found on [github](https://github.com/amazonlinux/amazon-linux-2023/issues/56#issuecomment-1006234810) and tested locally that it results in a working build. I also bumped the version number of k3s to the latest stable patch of the same minor release. 
Will kick off AMI builds of the failed previous builds once this is merged

fix install script

---

install/reboot.sh

Closes https://linear.app/sourcegraph/issue/REL-406/gcp-image-docs-do-not-produce-a-working-gcp-deployment
Closes https://linear.app/sourcegraph/issue/REL-388/dns-resolution-issue-for-private-endpoint-in-k3s-environment
This allows for both GCP and AWS images to resolve internal DNS endpoints in a VPC that are available via the VPC metadata endpoint `169.254.169.254`.
This is due to how modern linux systems run an internal resolver via systemd which is not able to be accessed by coreDNS, the DNS service in our k3s cluster.
CoreDNS also does not sequentially work it's way through the list of resolvers it is provided via the host, but instead does a "sticky round robin" meaning if given `your-internal-dns-server` and `8.8.8.8`, coreDNS will try one of those at random. If it doesn't get an …

Fix: internal DNS failure

---

install/reboot.sh

- Moved the k3s_not_running check earlier in the script to catch and remediate the case where k3s is failing to start, even if the AMI version matches the data volume version (ex. attaching data volume to different instance at the same version)
- Moved override_coredns to the start of the script fix the DNS issue before any network traffic in the script
- Created the check_pod_statuses function to provide more visibility on pod state throughout the script
- Reordered the Helm update sequence to prioritize getting the latest Helm charts from our Helm repo server, over using the Helm charts on the local disk, only if the instance can access the server, so that customer instances get the latest Helm charts for their Sourcegraph version, in case we release a fix
- Added a fallback so that the …

Fix reboot.sh for attaching data volume to different instance at the same version

---

.github/workflows/backport.yml
.gitignore

Add GitHub action for backporting PRs in line with out monorepo.
Sneak in Jetbrains `.idea` folder to the git ignore as well.

Add GH action for backports

---

.buildkite/pipeline.yml
volume_cleanup.sh

Found that I had this clean up script already in the repo, so I'm adding it to the repo officially. 
I then call this script from the pipeline so it automatically cleans up the volumes. However, I'm a bit worried it'll clean up all the volumes and we may need one?

fix: clean up volumes through CI

---

install/install.sh
install/override.burst.yaml
packer/aws-latest/aws-builder.pkr.hcl
packer/aws-latest/init.sh
packer/aws-latest/install.sh
packer/aws/aws-builder.pkr.hcl
packer/gcp/gcp-builder.pkr.hcl
packer/gcp/init.sh

Currently our AMI images implement a specific `override.<size>.yaml` file for a given T-shirt sizing. While this allows us to offer flexible fixed sizing options, it means we need to have 5 different AMI images per release (XS, S, M, L, XL).
While this was not an issue when Sourcegraph followed a quarterly release cycle, with our current 2x monthly release cycle - or possibly more - the storage and AWS public AMI quota management of additional images has lead to increase cloud expenses.
Furthermore, while 5 sizing options cover a majority of customers, customers looking to use an EC2 instance size outside of our recommended sizes are forced to manually modify their `override` file, or face wasting compute resources due to imposed service limits in our internal K8s setup.
This PR removes …

feature(rel): switch to Burstable k8s QOS 

---

packer/aws/aws-builder.pkr.hcl

Images are no longer sized so remove duplicate builds and remove image size in description and name

feat(rel): change build names for single image

---

packer/aws/aws-builder.pkr.hcl

Since AMIs are no longer sized, modify naming to drop artifacts from the sizing

fix(rel): update names to reflect dropping of sizing

---

packer/aws/aws-builder.pkr.hcl

This should fix the CI issue that is currently causing the build pipeline to fail. Furthermore, this cuts down the files baked into the iamge to only those needed.

fix(rel): fix CI pipeline error

---

install/override.L.yaml
install/override.M.yaml
install/override.S.yaml
install/override.XL.yaml
install/override.XS.yaml
install/override.burst.yaml

Enables Jaeger by default for AMI instances. 
As the intent of the AMI is minimize configuration requirements below the web UI, deploying the Jaeger container in the AMI by default removes this step. It also results in the image getting baked into the AMI, so that customers who cannot pull images from Docker Hub can still use HTTP traces when needed to troubleshoot issues with their instance. 
After / if this PR is merged, a corresponding update to the HTTP tracing docs will be made, to include the AMI https://sourcegraph.com/docs/admin/observability/tracing
Tested manually on AWS AMI

Enable Jaeger on AMI instances

---

generate-changelog.py

See title as well as https://github.com/sourcegraph/deploy/pull/130

fix(release): remove size header from changelog generation on release

---

install/override.L.yaml
install/override.M.yaml
install/override.S.yaml
install/override.XL.yaml
install/override.XS.yaml
install/override.burst.yaml

The embeddings service has been deprecated since v5.7, we should disable it

Disable deprecated embeddings service

---

.buildkite/pipeline.yml

This PR adds tagging the `deploy` repo at the time we build and release new AMIs. I don't believe the code is changing much in this repo on Sourcegraph version changes, but if it does this helps us keep track of it.
This is tagging the branch opened when we create a PR to update the Changelog, as the given version tag

chore(release): add tagging to the AMI build pipeline

---

install/override.L.yaml
install/override.M.yaml
install/override.S.yaml
install/override.XL.yaml
install/override.XS.yaml
install/override.burst.yaml

Linear issue [REL-812: Update deployment types](https://linear.app/sourcegraph/issue/REL-812/update-deployment-types)
Switching DEPLOY_TYPE from k3s to AMI, so that we can find these customer instances in telemetry more clearly.

Chore: Fix deployment types in telemetry
