README.md

Manually tested to confirm the AMIs are working as expected.
PR to update AMI ID in docs: https://github.com/sourcegraph/sourcegraph/pull/42318

Update AMI ID for Size S and M

---

CHANGELOG.md
README.md
doc/development.md
install/install.sh
install/reboot.sh
packer/aws/aws-builder.pkr.hcl
packer/build-variables.hcl

Update changelog and scripts used for 4.1.0 release

4.1.0 AMI release

---

packer/build-variables.hcl
packer/gcp/gcp-builder.pkr.hcl
packer/gcp/init.sh
packer/gcp/install.sh

Close https://github.com/sourcegraph/sourcegraph/issues/43505
Add scripts for bundling Setup Wizard to gcp images.
demo: https://www.loom.com/share/b011cfe961f24eaf9c29312e82a2e6df?t=109

Packer build for gcp images with Setup Wizard

---

doc/development.md

just some minor dev docs improvements

improve development docs

---

CHANGELOG.md

release v4.3.1 - add AWS ID by region
https://github.com/sourcegraph/sourcegraph/issues/46617

release v4.3.1

---

CHANGELOG.md

https://github.com/sourcegraph/sourcegraph/issues/46749

release v4.4.0

---

lint.sh
packer/gcp/gcp-builder.pkr.hcl
packer/gcp/init.sh
packer/gcp/install.sh

- Modified gcp build process to remove setup wizard
- Updated script to build an image per t-shirt size
- Ran the packer formatter + linter

Updated  GCP images

---

CHANGELOG.md

Update `CHANGELOG.md` with 5.0.0 release AMIs

Release: release 5.0.0 AMIs

---

CHANGELOG.md

Release v5.0.3 AWS images

---

CHANGELOG.md

Release v5.0.4 AWS images

---

CHANGELOG.md

Release 5.0.6 AWS machine images

Release 5.0.6 AWS AMIs

---

install/install.sh
install/reboot.sh
install/scripts/k3s/install.sh
install/scripts/k3s/local.sh
install/scripts/k3s/reboot.sh
packer/aws-latest/install.sh
packer/gcp/install.sh

Installers + reboot scripts for each machine image type for native k8s executors

Installer for executors

---

CHANGELOG.md

Release 5.1.4

---

install/reboot.sh
install/scripts/k3s/reboot.sh

- Fix conditional logic to update /mnt/data/.sourcegraph_version

Fix version not being updated

---

CHANGELOG.md

Release v5.1.6 of Sourcegraph AMIs

Release v5.1.6 AMIs

---

CHANGELOG.md

Release for Sourcegraph 5.1.7 AMI

release: 5.1.7

---

CHANGELOG.md
README.md

release 5.1.8

---

CHANGELOG.md

Release Sourcegraph 5.1.9 AMIs

release: sourcegraph 5.1.9 AMIs

---

CHANGELOG.md

Release 5.2.0 Sourcegraph AMIs

release 5.2.0

---

CHANGELOG.md

release 5.2.1

---

CHANGELOG.md

Release Sourcegraph v5.2.3 AMIs

release: 5.2.3

---

CHANGELOG.md

release: 5.2.4

---

CHANGELOG.md

release: 5.2.5

---

CHANGELOG.md
install/install.sh
install/scripts/k3s/install.sh
packer/gcp/init.sh

Update k3s version to 1.29.0 across machine images

AMI: update k3s version to 1.29.0 across machine images

---

CHANGELOG.md

- Update internal K3s to version 1.29.0
- af-south-1: ami-0f3d3598b486e2445
- ap-east-1: ami-09d188c24da847a1e
- ap-northeast-1: ami-0417c0f0460d04c22
- ap-northeast-2: ami-08100fb5bb6d0b1fd
- ap-south-1: ami-0afabaecca0511f66
- ap-southeast-1: ami-02628b1e33177117b
- ap-southeast-2: ami-07933c35258b484ca
- ap-southeast-3: ami-0852093d1f0c13301
- ca-central-1: ami-00ce9bfd9d6556963
- eu-central-1: ami-08da590bc09e9dc22
- eu-north-1: ami-0da91937d23b1d36f
- eu-south-1: ami-0635153d225f555b6
- eu-west-1: ami-09950878d0a04a720
- eu-west-2: ami-0e027066c7eb136ee
- eu-west-3: ami-0ccc10fef5fb270a1
- me-central-1: ami-03beee2bc1532ed03
- me-south-1: ami-0e43881644b6641bf
- sa-east-1: ami-05c2f20b2b2d9f90b
- us-east-1: ami-072fe312c4a937b64
- us-east-2: ami-01606c3063200c19f
- us-west-1: …

Release 5.2.7 AWS AMIs

---

CHANGELOG.md

Release Sourcegraph 5.3.0 AMIs

Release 5.3.0

---

CHANGELOG.md

Release 5.3.1 Sourcegraph AMIs

Release 5.3.1

---

CHANGELOG.md

Fix: markdown list formatting

---

CHANGELOG.md

Release Sourcegraph 5.3.2 AMIs

Release 5.3.2

---

CHANGELOG.md

Release Sourcegraph 5.3.3 AMIs

release 5.3.3

---

CHANGELOG.md

release 5.3.9104

---

CHANGELOG.md

This time featuring creation from the correct AWS account...

docs(changelog): Release AWS AMI hashes

---

CHANGELOG.md

Changelog Hashes for v5.3.12303

---

CHANGELOG.md

Changelog Hashes for v5.4.2198

---

packer/aws/aws-builder.pkr.hcl

Fixes dev builds that I previously broke.

Fix Dev Builds

---

.buildkite/pipeline.yml
CHANGELOG.md

Changelog Hashes for v5.4.7765

---

install/reboot.sh

Making the script easier to read

Adding more comments to reboot.sh

---

CHANGELOG.md

Changelog Hashes for v5.7.0

---

CHANGELOG.md

Changelog Hashes for v5.5.1337

---

CHANGELOG.md

Changelog Hashes for v5.5.2463

---

CHANGELOG.md

Changelog Hashes for v5.5.3738

---

CHANGELOG.md

Changelog Hashes for v5.5.3956

---

CHANGELOG.md

Changelog Hashes for v5.6.185

---

CHANGELOG.md

Changelog Hashes for v5.6.2535

---

CHANGELOG.md

Changelog Hashes for v5.7.2474

---

CHANGELOG.md

Changelog Hashes for v5.8.0

---

CHANGELOG.md

chore(release): update changelog with 5.8.1 images

---

CHANGELOG.md

Changelog Hashes for v5.8.1579

---

CHANGELOG.md

Changelog Hashes for v5.9.347

---

install/install.sh
install/override.yaml

Test burstable QOS size on AWS AMI

Test burstable QOS on AMIS

---

.tool-versions

Add `.tool-versions` file for easy env setup with `asdf` or `mise`.

Add tool-versions file for asdf/mise

---

install/install.sh
install/override.XS.yaml

chore(rel): Undo QOS testing

---

CHANGELOG.md

Merge AMI list back into `main` changelog.

chore(rel): Add recent releases to changelog

---

CHANGELOG.md

Changelog Hashes for v5.10.2832

---

README.md

Update README information with sizing changes

chore(docs): update readme with sizing info

---

CHANGELOG.md

Changelog Hashes for v6.1.5633

---

CHANGELOG.md

Changelog Hashes for v6.2.1106

---

CHANGELOG.md

Changelog Hashes for v6.4.3889

---

CHANGELOG.md

Changelog Hashes for v6.5.2654
